### ISSUE TITLE
Stadia Controller Firmware / Bootloader 

### ISSUE THREAD

**Issue by thijsk** [googlestadia/kernel#4]
I know this isn't the right repository, but I hope this plea can be passed on to the right people.

Since there is already a lot of nice open source work here I would like to ask for either an update to the stadia controller that enables Bluetooth, or at least an update that enables a way for developers to load their own software onto the controller. This way the controllers wont go to waste after stadia shuts down, because they are quite capable devices and having them go to the landfill would be a huge waste of resources.

Many thanks for your efforts,
Regards, 
Thijs

**Comment by jfthibert** [comment]
Hi Thijs,

You can find the bluetooth update at [stadia.com/controller](http://stadia.com/controller)

**Comment by myst729** [comment]
@jfthibert Thank you for the info. The controller is very nice and can still function out of Stadia rather than become e-waste. Is it possible that the controller's bluetooth mode firmware be open sourced? I think there are still chances of improvements. I see a lot of discussions here and there (e.g. https://github.com/libsdl-org/SDL/issues/7224) and the community would like to help.
